# Generated by Django 4.1.6 on 2023-02-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('percent', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('percent', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('u', 'USD'), ('r', 'RUB')], default='u', max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='test_app.discount')),
                ('item', models.ManyToManyField(to='test_app.item')),
                ('tax', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='test_app.tax')),
            ],
        ),
    ]
