# Generated by Django 4.1.6 on 2023-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_order_total_price_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
