# Generated by Django 4.1.6 on 2023-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_discount_percent_alter_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='tax',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
