# Generated by Django 4.1.6 on 2023-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_discount_percent_alter_discount_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='size',
        ),
        migrations.AddField(
            model_name='discount',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tax',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
