# Generated by Django 4.1.6 on 2023-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_remove_discount_size_remove_tax_size_discount_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='country',
            field=models.CharField(choices=[('ru', 'Russia'), ('us', 'USA')], max_length=2),
        ),
    ]
