# Generated by Django 4.1.6 on 2023-02-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_tax_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
