# Generated by Django 4.1.6 on 2023-02-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
